services:
  nest_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./src:/usr/src/app/src
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data-prod:/data/db

volumes:
  mongo-data-prod:
    driver: local